---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-report
  labels:
    app: backend-report
spec:
  replicas: 1
  # Стратегия развёртывания. Recreate — удалит сначала все старые поды 
  # Есть и более гибкая стратегии, например, RollingUpdate, которая будет обновлять поды порциями  
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: backend-report
  template:
    metadata:
      labels:
        app: backend-report
    spec:
      containers:
        - name: backend-report
          image: gitlab.praktikum-services.ru:5050/aspedan/sausage-store/sausage-store-report:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_CLOUD_VAULT_HOST
              value: sausage-store.alexpedan.ml
            - name: SPRING_CLOUD_VAULT_TOKEN
              value: myroot
            - name: spring.datasource.url
              value: jdbc:postgresql://rc1b-ddr4cnexjyd5olyl.mdb.yandexcloud.net:6432/sausages
            - name: spring.datasource.username
              value: alexspedan
            - name: spring.datasource.password
              value: Testusr1234
            - name: SPRING_CLOUD_VAULT_SCHEME
              value: http
            - name: SPRING_FLYWAY_ENABLED
              value: "false"
            - name: spring.application.name
              value: sausage-store-report
          ports:
            - name: backend-report
              containerPort: 8081
      imagePullSecrets:
        - name: regcred
