---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  # Стратегия развёртывания. Recreate — удалит сначала все старые поды 
  # Есть и более гибкая стратегии, например, RollingUpdate, которая будет обновлять поды порциями  
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
        #  image: gitlab.praktikum-services.ru:5050/aspedan/sausage-store/sausage-store-multistage:latest
        #  image: gitlab.praktikum-services.ru:5050/aspedan/sausage-store/sausage-frontend:latest
          image: gitlab.praktikum-services.ru:5050/aspedan/sausage-store/sausage-store-kuber:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: VAULT_HOST
              value: http://sausage-store.alexpedan.ml:8200/
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: vault_token
          ports:
            - name: frontend
              containerPort: 80
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: frontend

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kuber.conf
data:
  kuber.conf: |
    server {

      listen 80;

      location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
      }

      location /api {
          proxy_pass http://localhost;
      }
    }
    {{ end }}
