---
apiVersion: v1
kind: Secret
metadata:
  name: vault
data:
  host: dmF1bHQuYWxleHBlZGFuLm1sCg==
  vault_token: bXlyb290
type: Opaque

---
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
spec:
  limits:
  - default:
      memory: 512Mi
    defaultRequest:
      memory: 512Mi
    type: Container
